package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/gorilla/websocket"
)

const (
	Role = "C"
)

type allocation struct {
	Uids map[string]int `json:"allocation"`
}



var (
	ALGO_TEST_LINK = "ws://localhost:13000/join"
	ALGO_LIVE_LINK = "wss://ipd-allocator-1.onrender.com/ws"
)

func main() {
	// Setup signal handling
	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, os.Interrupt, syscall.SIGTERM)

	var edge_connection sync.WaitGroup
	var worker_done sync.WaitGroup

	// Parse flags
	useSplit := false
	numRounds := 3
	numEpochs := 1
	batchSize := 32
	learningRate := 0.001

	args := os.Args[1:]
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "-split" {
			useSplit = true
		} else if arg == "-rounds" && i+1 < len(args) {
			fmt.Sscanf(args[i+1], "%d", &numRounds)
			i++
		} else if arg == "-epochs" && i+1 < len(args) {
			fmt.Sscanf(args[i+1], "%d", &numEpochs)
			i++
		} else if arg == "-batch" && i+1 < len(args) {
			fmt.Sscanf(args[i+1], "%d", &batchSize)
			i++
		} else if arg == "-lr" && i+1 < len(args) {
			fmt.Sscanf(args[i+1], "%f", &learningRate)
			i++
		}
	}

	fmt.Printf("Configuration: Rounds=%d, Epochs=%d, Batch=%d, LR=%f\n", numRounds, numEpochs, batchSize, learningRate)

	// Set up directory - default to 'processed_data' if generated by preprocessor
	dir := "/home/mihir/Desktop/Final_IPD/IPD-F/mnist_jpg"

	// Locate DataPreprocessor.py
	preprocessorScript := "DataPreprocessor.py"
	if _, err := os.Stat(preprocessorScript); os.IsNotExist(err) {
		if _, err := os.Stat("../" + preprocessorScript); err == nil {
			preprocessorScript = "../" + preprocessorScript
		} else {
			log.Printf("Warning: DataPreprocessor.py not found in . or ..")
		}
	}

	// Invoke DataPreprocessor
	cmdLine := fmt.Sprintf("python3 %s --data_dir %s", preprocessorScript, dir)
	if useSplit {
		cmdLine += " --split"
	}

	fmt.Printf("Preprocessing data (Split=%v) using %s...\n", useSplit, preprocessorScript)
	cmd := exec.Command("sh", "-c", cmdLine)
	var out bytes.Buffer
	cmd.Stdout = &out
	if err := cmd.Run(); err != nil {
		log.Fatalf("Preprocessor failed: %v", err)
	}

	// The preprocessor prints the training directory to stdout (last line)
	outputLines := strings.Split(strings.TrimSpace(out.String()), "\n")
	trainDir := strings.TrimSpace(outputLines[len(outputLines)-1])
	fmt.Printf("Using training directory: %s\n", trainDir)

	n, files, err := get_data(trainDir)
	if err != nil {
		log.Fatal("Error while reading dir: ", err)
	}

	// Detect num_classes by counting subdirectories in trainDir (if nested) or reading labels.json
	numClasses := 10 // Default fallback
	if entries, err := os.ReadDir(trainDir); err == nil {
		classCount := 0
		for _, entry := range entries {
			if entry.IsDir() {
				classCount++
			}
		}
		if classCount > 0 {
			numClasses = classCount
		} else {
			// Check for labels_train.json if it's flat
			labelsPath := filepath.Join(trainDir, "labels_train.json")
			if data, err := os.ReadFile(labelsPath); err == nil {
				var labelData struct {
					NumClasses int `json:"num_classes"`
				}
				if err := json.Unmarshal(data, &labelData); err == nil && labelData.NumClasses > 0 {
					numClasses = labelData.NumClasses
				}
			}
		}
	}
	fmt.Printf("Detected %d classes\n", numClasses)

	// Get number of workers
	var numWorkers int
	MaxWorkers := runtime.NumCPU()
	fmt.Printf("Enter number of workers (recommended less than %d for your device)\nWorkers: ", MaxWorkers)
	fmt.Scan(&numWorkers)

	// Create room ID and connect to algorithm service
	room_id := create_uid()
	fmt.Println("Connection_id:", room_id)

	algo_service, _, err := websocket.DefaultDialer.Dial(ALGO_LIVE_LINK, nil)
	if err != nil {
		log.Fatal("Error while creating connection to algorithm service: ", err)
	}
	defer algo_service.Close()

	// Send initial connection message
	postbody := map[string]interface{}{
		"role":      Role,
		"room_id":   room_id,
		"num_edges": numWorkers,
	}

	if err := algo_service.WriteJSON(postbody); err != nil {
		log.Fatal("Error while writing to connection: ", err)
	}

	// Handle keepalive for algorithm service
	alive := make(chan struct{})
	defer close(alive)

	go func() {
		ticker := time.NewTicker(30 * time.Second) // Increased from 5s for long training
		defer ticker.Stop()

		for {
			select {
			case <-ticker.C:
				if err := algo_service.WriteControl(websocket.PingMessage, []byte{}, time.Now().Add(30*time.Second)); err != nil {
					log.Println("Failed to send ping: ", err)
					return
				}
			case <-alive:
				return
			}
		}
	}()

	// Read allocation from algorithm service
	var allocate allocation
	if err := algo_service.ReadJSON(&allocate); err != nil {
		log.Fatal("Error while reading from connection: ", err)
	}
	fmt.Println("Response from algo service: ", allocate)

	// Keep reading from algo_service to handle pings/pongs
	go func() {
		for {
			if _, _, err := algo_service.NextReader(); err != nil {
				log.Printf("Algo service read error: %v", err)
				return
			}
		}
	}()

	// Process allocation
	edge_id := make([]string, 0, len(allocate.Uids))
	for id := range allocate.Uids {
		edge_id = append(edge_id, id)
	}

	for _, id := range edge_id {
		fmt.Printf("ID: %s Weights: %d\n", id, allocate.Uids[id])
	}

	// Initialize worker pool
	// Use a large buffer for resultchan to avoid blocking
	resultchan := make(chan Result, n + numWorkers*numRounds*2) 
	wp := Workerpool{resultchan: resultchan}
	wp.start_pool(numWorkers, n, edge_id, allocate.Uids, &edge_connection, &worker_done)

	// Wait for workers to connect
	edge_connection.Wait()

	globalModelPath := "" // Will be updated after each round

	// ==========================================
	// FEDERATED LEARNING LOOP
	// ==========================================
	// Create a unique timestamp for this training session
	overallStartTime := time.Now().Format("20060102_150405")

	for round := 0; round < numRounds; round++ {
		roundFolder := fmt.Sprintf("%s_round_%d", overallStartTime, round+1)
		fmt.Printf("\n==================================================\n")
		fmt.Printf("STARTING FEDERATED ROUND %d / %d\n", round+1, numRounds)
		fmt.Printf("Subdirectory: %s\n", roundFolder)
		fmt.Printf("==================================================\n")

		// 1. Send Hyperparameters and Round Folder
		params_map := map[string]interface{}{
			"epochs":        numEpochs,
			"batch_size":    batchSize,
			"learning_rate": learningRate,
			"num_classes":   numClasses,
		}
		
		if globalModelPath != "" {
			params_map["model_path"] = filepath.Base(globalModelPath)
		}

		paramsJson, _ := json.Marshal(params_map)
		paramsStr := string(paramsJson)

		// Broadcast params and folder to all workers
		for i := 0; i < numWorkers; i++ {
			wp.workers[i].req_chan <- Request{
				is_params:    true, 
				params:       paramsStr,
				round_folder: roundFolder,
			}
		}

		// 2. Distribute Data (Round 0 only)
		filesSent := 0
		if round == 0 {
			fmt.Printf("Distributing %d data files...\n", len(files))
			for _, file_path := range files {
				worker := wp.pickWorker()
				worker.req_chan <- Request{f: file_path}
				filesSent++
			}
		} else {
			fmt.Printf("Skipping data distribution (already done in Round 1)\n")
		}

		if round > 0 && globalModelPath != "" {
			fmt.Printf("Broadcasting global model to ALL workers: %s\n", globalModelPath)
			modelFilename := filepath.Base(globalModelPath)
			for i := 0; i < numWorkers; i++ {
				fmt.Printf("  -> Sending model to Worker %d...\n", i)
				wp.workers[i].req_chan <- Request{
					f:           globalModelPath,
					remote_name: modelFilename,
				}
				filesSent++ 
			}
		}

		// 4. Trigger Training
		fmt.Printf("Triggering training on all %d workers...\n", numWorkers)
		for i := 0; i < numWorkers; i++ {
			wp.workers[i].req_chan <- Request{is_trigger: true}
		}

		// 5. Wait for Completion
		modelsReceived := 0
		uploadsCompleted := 0
		
		fmt.Printf("Waiting for results... (Expect %d uploads, %d models)\n", filesSent, numWorkers)
		
		for modelsReceived < numWorkers {
			result := <-resultchan
			switch result.result {
			case SUCCESS:
				uploadsCompleted++
				if uploadsCompleted % 100 == 0 || uploadsCompleted == filesSent {
					fmt.Printf("  [Round %d] Upload progress: %d/%d\n", round+1, uploadsCompleted, filesSent)
				}
			case MODEL_RECEIVED:
				modelsReceived++
				fmt.Printf("  [Round %d] Worker %d finished training and returned model (%d/%d)\n", round+1, result.worker_id, modelsReceived, numWorkers)
			}
		}

		fmt.Printf("Round %d training completed. Aggregating results...\n", round+1)
		
		// 6. Aggregation
		// Prepare and send aggregation data to the API server
		edgeIDs := make([]string, 0, len(allocate.Uids))
		for id := range allocate.Uids {
			edgeIDs = append(edgeIDs, id)
		}

		requestData := map[string]interface{}{
			"uids":      edgeIDs,
			"directory": roundFolder,
		}
		
		jsonData, err := json.Marshal(requestData)
		if err != nil {
			log.Fatalf("Error marshaling aggregation request: %v", err)
		}

		apiURL := "http://localhost:8000/receive_uids"
		resp, err := http.Post(apiURL, "application/json", bytes.NewBuffer(jsonData))
		if err != nil {
			log.Printf("Error posting to aggregator: %v", err)
			continue
		}
		
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		
		var aggResult map[string]interface{}
		json.Unmarshal(body, &aggResult)
		
		if resp.StatusCode == http.StatusOK {
			if modelPath, ok := aggResult["model_path"].(string); ok {
				fmt.Printf("New Global Model: %s\n", modelPath)
				globalModelPath = modelPath
				
				// 7. Evaluation
				if true { // Evaluate every round
					testDir := filepath.Join(dir, "test")
					fmt.Printf("Evaluating model on %s...\n", testDir)
					
					// Locate evaluate.py logic (reused)
					evalScript := "evaluate.py"
					if _, err := os.Stat(evalScript); os.IsNotExist(err) {
						if _, err := os.Stat("main/" + evalScript); err == nil {
							evalScript = "main/" + evalScript
						}
					}
					
					cmdArgs := []string{evalScript, 
						"--model-path", modelPath, 
						"--data-dir", testDir,
						"--num-classes", fmt.Sprintf("%d", numClasses),
					}
					
					if numClients, ok := aggResult["num_clients"].(float64); ok {
						cmdArgs = append(cmdArgs, "--num-clients", fmt.Sprintf("%.0f", numClients))
					}

					evalCmd := exec.Command("python3", cmdArgs...)
					evalCmd.Stdout = os.Stdout
					evalCmd.Stderr = os.Stderr
					evalCmd.Run() // Ignore error, just run
				}
			}
		} else {
			log.Printf("Aggregation failed: %v", aggResult)
		}
	} // End of Round Loop

	// Close worker channels to shut them down
	fmt.Println("Training complete. Shutting down workers...")
	for i := 0; i < numWorkers; i++ {
		close(wp.workers[i].req_chan)
	}

	// Wait for all workers to finish
	worker_done.Wait()
	<-signalChan
	log.Println("Shutting down...")

}
